version = 1
disable_existing_loggers = false

[handlers.consoleHandler]
level = "DEBUG"
class = "logging.StreamHandler"
formatter ="consoleFormatter"


[handlers.coreHandler]
level = "INFO"
class = "logging.handlers.RotatingFileHandler"
filename = "logs/core/core.log"
maxBytes = 104857600
backupCount = 5
formatter = "coreFormatter"

[handlers.authHandler]
level = "INFO"
class = "logging.handlers.RotatingFileHandler"
filename = "logs/auth/auth.log"
maxBytes = 104857600
backupCount = 10
formatter = "authFormatter"

[formatters.consoleFormatter]
format = "%(levelname)s %(asctime)s %(module)s %(message)s"
datefmt = "%Y-%m-%d-%H-%M-%S"

[formatters.coreFormatter]
format = "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
datefmt = "%Y-%m-%d-%H-%M-%S"


[formatters.authFormatter]
format = "[%(levelname)s] [%(asctime)s] [%(module)s] [%(process)d] [%(thread)d] [%(message)s]"
datefmt = "%Y-%m-%d-%H-%M-%S"




[loggers.core]
handlers = ["coreHandler", "consoleHandler"]
level = "INFO"
propagate = false


[loggers.auth]
handlers = ["authHandler"]
level = "INFO"
propagate = false
